# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TtnLwMigrate < Formula
  desc "Migrate from other LoRaWAN network servers to The Things Stack"
  homepage "https://www.thethingsnetwork.org"
  version "0.11.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.11.1/lorawan-stack-migrate_0.11.1_darwin_arm64.tar.gz"
      sha256 "63ed8ae3a2cebf8743bb9aefada76174a85ab951de3411b55defacf0f4beec35"

      def install
        bin.install "ttn-lw-migrate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.11.1/lorawan-stack-migrate_0.11.1_darwin_amd64.tar.gz"
      sha256 "26ff54279a14fc31a3405e9883e2ecd01d8960145f9728240bf22c5fa3f65127"

      def install
        bin.install "ttn-lw-migrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.11.1/lorawan-stack-migrate_0.11.1_linux_arm64.tar.gz"
      sha256 "4a411eb5adb830c5f855a2d819dd4b98aa51fee8bffc22eb46dc7118fe7974bb"

      def install
        bin.install "ttn-lw-migrate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.11.1/lorawan-stack-migrate_0.11.1_linux_amd64.tar.gz"
      sha256 "d6d32a46179f1e07929b90be44a6b6caf98788df41fe5528b18155a2bc6759c7"

      def install
        bin.install "ttn-lw-migrate"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.11.1/lorawan-stack-migrate_0.11.1_linux_armv6.tar.gz"
      sha256 "ae1b7c2c069bb33bedd416e53d0c4975beab93df6280d06d5a6bffda652e24e3"

      def install
        bin.install "ttn-lw-migrate"
      end
    end
  end
end
