# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TtnLwMigrate < Formula
  desc "Migrate from other LoRaWAN network servers to The Things Stack"
  homepage "https://www.thethingsnetwork.org"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.10.0/lorawan-stack-migrate_0.10.0_darwin_arm64.tar.gz"
      sha256 "9b63f589d5b36415fca40d9e324e1c384ddd09ae007adcb7851679db53e9b505"

      def install
        bin.install "ttn-lw-migrate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.10.0/lorawan-stack-migrate_0.10.0_darwin_amd64.tar.gz"
      sha256 "21c836b032f36e957178ded7ea4800d2900043785fe067d94856c1e6126d8699"

      def install
        bin.install "ttn-lw-migrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.10.0/lorawan-stack-migrate_0.10.0_linux_arm64.tar.gz"
      sha256 "2ac24a14802ef734db490c55d9d80adc49a270ea70391f7733feaf9d76072bd7"

      def install
        bin.install "ttn-lw-migrate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.10.0/lorawan-stack-migrate_0.10.0_linux_amd64.tar.gz"
      sha256 "81d9fc2cd96d7e8bd37d92af5da20232a4f1ccc2bbbfef5a62b93cf114fc6c6f"

      def install
        bin.install "ttn-lw-migrate"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.10.0/lorawan-stack-migrate_0.10.0_linux_armv6.tar.gz"
      sha256 "9c3173aedaab90c0b6586ced195ab13bae37ccc68ba1ef3e290be8d7dcb7b5d8"

      def install
        bin.install "ttn-lw-migrate"
      end
    end
  end
end
