# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TtnLwMigrate < Formula
  desc "Migrate from other LoRaWAN network servers to The Things Stack"
  homepage "https://www.thethingsnetwork.org"
  version "0.5.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.5.0/lorawan-stack-migrate_0.5.0_darwin_amd64.tar.gz"
    sha256 "e8eb65fce25f4e6a01d8413ce04affcbc1e720eb0ceb0f2b6798703881938d9b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.5.0/lorawan-stack-migrate_0.5.0_linux_amd64.tar.gz"
    sha256 "74b8b0f374adeead2cef6773afa74aedea9050d9e300a7e856385d4254ff3754"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.5.0/lorawan-stack-migrate_0.5.0_linux_armv6.tar.gz"
    sha256 "b2df5695ceb3cea767a944be91fa9fda716bbde706c7ec8895f4b031ffa606f2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/download/v0.5.0/lorawan-stack-migrate_0.5.0_linux_arm64.tar.gz"
    sha256 "5a020ae66be164d99fa0eebcc32719bf997cbffaa7bf753e2749856ccd3d7aa7"
  end

  def install
    bin.install "ttn-lw-migrate"
  end
end
