# This file was generated by GoReleaser. DO NOT EDIT.
class TtnLwStack < Formula
  desc "The Things Stack for LoRaWAN"
  homepage "https://www.thethingsnetwork.org"
  version "3.10.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/TheThingsNetwork/lorawan-stack/releases/download/v3.10.7/lorawan-stack_3.10.7_darwin_amd64.tar.gz"
    sha256 "ded8dd5c60fcfa6ba56aecab19943e8813795dbd8fcf7a942523935361c43ed6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/TheThingsNetwork/lorawan-stack/releases/download/v3.10.7/lorawan-stack_3.10.7_linux_amd64.tar.gz"
      sha256 "23c85b1b1c59334d19e7a16f2b8b906d99d429f0550cbc80df270ba3a5eb781c"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TheThingsNetwork/lorawan-stack/releases/download/v3.10.7/lorawan-stack_3.10.7_linux_arm64.tar.gz"
        sha256 "ee4d0d9d26baaf3f4c859d2a58d056d96fb8cc871df00b53a51e58b05aac17c6"
      else
        url "https://github.com/TheThingsNetwork/lorawan-stack/releases/download/v3.10.7/lorawan-stack_3.10.7_linux_armv6.tar.gz"
        sha256 "e8fef323abc66efeb403d290b656373b3464001542c84f32e9a9dc54dc11f52e"
      end
    end
  end
  
  conflicts_with "ttn-lw-cli"

  def install
    bin.install "ttn-lw-cli"
    libexec.install %w[ttn-lw-stack public]
    env = {
        :TTN_LW_HTTP_STATIC_SEARCH_PATH => libexec/"public"
    }
    (bin/"ttn-lw-stack").write_env_script libexec/"ttn-lw-stack", env
    bash_completion.install "config/completion/bash/ttn-lw-cli"
    zsh_completion.install "config/completion/zsh/_ttn-lw-cli"
    fish_completion.install "config/completion/fish/ttn-lw-cli.fish"
    bash_completion.install "config/completion/bash/ttn-lw-stack"
    zsh_completion.install "config/completion/zsh/_ttn-lw-stack"
    fish_completion.install "config/completion/fish/ttn-lw-stack.fish"
  end
end
